logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
        descriptor: TRACE

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cinema_tickets_movies?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    password: ${db_password}
    username: ${db_username}

  sql:
    init:
      mode: never

  cinema_tickets:
    default.admin.pass: ${DEFAULT_ADMIN_PASS:123456}
    remember.me.key: ${REMEMBER_ME_KEY:123456}

  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8081